#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vsftpd[-1]
	add ucitrack vsftpd
	set ucitrack.@vsftpd[-1].init=vsftpd
	commit ucitrack
EOF

uci set vsftpd.listen.enable4='0'
uci commit vsftpd

rm -f /tmp/luci-vsftpd
exit 0
